javadoc /z/CloudStorage/_daniel/IUS\ Computer\ Science/Spring\ 2020/C202\ Intro\ To\ Software\ Systems/assignments/HW3_ReadingWritingToFiles/src/app/*.java \
-tag custom.application_name:a:"Application Name" \
-tag custom.class_name:a:"Class Name" \
-tag custom.method_name:a:"Method Name" \
-tag custom.author:a:"Author" \
-tag custom.instructor:a:"Instructor" \
-tag custom.course:a:"Course" \
-tag custom.date_started:a:"Date Started" \
-tag custom.date_due:a:"Date Due" \
-tag custom.class_notes:a:"Class Notes" \
-tag custom.method_notes:a:"Method Notes" \
-tag custom.pre_condition:a:"Pre-Condition" \
-tag custom.post_condition:a:"Post-Condition" \
-tag custom.javadoc_tags:a:"JAVADocs Custom Tags" 